Fix
```
sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v2.1.2
WARNING: The config value `version' has type `bytes', defaults to `str'.
WARNING: The config value `release' has type `bytes', defaults to `str'.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 17 source files that are out of date
updating environment: 17 added, 0 changed, 0 removed
reading sources... [ 11%] assertions
Exception occurred:
  File "/usr/lib/python3.7/site-packages/docutils/nodes.py", line 355, in __new__
    raise TypeError('expecting str data, not bytes')
TypeError: expecting str data, not bytes
The full traceback has been saved in /tmp/sphinx-err-uwsh5hbx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:55: html] Error 2
```